[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan cache:clear && php artisan filament:assets && php artisan config:cache && php artisan route:cache && php artisan migrate --force && apache2-foreground'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10