[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'php artisan config:cache && php artisan route:cache && php artisan migrate --force && apache2-foreground'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10